version: "3.1"

services:
    db:
        image: postgres:11.2
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: blog_db
        ports:
            - 5432:5432
